"""Use server_default=func.now() for refresh_tokens.created_at

Revision ID: 0550d02ea38d
Revises: 2a4730503583
Create Date: 2025-09-27 04:41:19.720665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0550d02ea38d'
down_revision: Union[str, None] = '2a4730503583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
