"""add refresh tokens table

Revision ID: 9e142dc30bdb
Revises: ad69ee5fb9fa
Create Date: 2025-09-26 19:05:20.123532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e142dc30bdb'
down_revision: Union[str, None] = 'ad69ee5fb9fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
