"""Add refresh_tokens table

Revision ID: ad69ee5fb9fa
Revises: 33c391d9a360
Create Date: 2025-09-26 17:15:21.807333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad69ee5fb9fa'
down_revision: Union[str, None] = '33c391d9a360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
